### ISSUE TITLE
add function to easily build the URL for creating a legend png

### ISSUE THREAD

**Issue by 7yl4r** [ropensci/rerddap#109]
Sometimes people want the colorbar to be separate from their plots (like when showing multiple plots [[1](https://dotis.github.io/FGBNMS_DBv3/#recent-7-day-mean-satellite-images)]). ERDDAP has legend rendering built-in using the `legend=Only` param to the `.png` endpoint.

An R function to use this functionality could be a useful addition to rerddap. It might look something like this:

```r
murSST <- rerrdap::griddap(
  sstInfo, 
  latitude = c(22., 51.), 
  longitude = c(-140., -105), 
  time = c("2017-01-01", "2017-01-02"), 
  fields = 'analysed_sst'
)

murSSTLegendImage <- rerrdap::get_legend_png(murSST)
```

Which could get a URL like this example with the `legend=Only` URL parameter:

```
https://coastwatch.pfeg.noaa.gov/erddap/griddap
  /jplAquariusSSS3MonthV5.png
  ?sss%5B(2015-03-21T00:00:00Z)%5D%5B(89.5):(-89.5)%5D%5B(-179.5):(179.5)%5D&
  .draw=surface&
  .vars=longitude%7Clatitude%7Csss&
  .colorBar=%7C%7C%7C%7C%7C&
  .bgColor=0xffccccff&
  .legend=Only
```

So that a legend can be easily displayed using ERDDAP's built-in functionality:

![example legend](https://coastwatch.pfeg.noaa.gov/erddap/griddap/jplAquariusSSS3MonthV5.png?sss%5B(2015-03-21T00:00:00Z)%5D%5B(89.5):(-89.5)%5D%5B(-179.5):(179.5)%5D&.draw=surface&.vars=longitude%7Clatitude%7Csss&.colorBar=%7C%7C%7C%7C%7C&.bgColor=0xffccccff&.legend=Only)

The tricky part here is that the lat, lon, & time are required; and they must be in range of the dataset.

**Comment by rmendels** [comment]
@7yl4r Thanks for the suggestion,  I will consider it.  Due to some other commitments,  even if I were to decide to do it will not be in the next month or so.  'rerddap' was designed with the idea of getting data into R for R to do the analyses and graphics.  Adding something like you suggest would be harder than you realize,  because people will want to control the graphics,  so I have to not only parse but check all the arguments, some ERDDAPs have custom colorbars so I would need to be able to check for those.  Programming for CRAN is harder than just programming for yourself,  because you have to check for all the thing people might do.

**Comment by 7yl4r** [comment]
The use-case here was specifically to using the WMS features of ERDDAP via leaflet. In that case the colorbar should match the displayed data because ERDDAP handles tile rendering on the server. 

Looking more at this package now I see you are right that this functionality is out-of-scope for rerddap. I will close this so that rerrdap can stay lightweight.

Please comment here or DM me if there is interest in our helper functions for displaying gridded ERDDAP data using leaflet, ggplot, and similar. We could publish them as separate packages or "plugins" for this package. rerrdap-leaflet, rerrdap-ggplot, etc.

**Comment by rmendels** [comment]
@7yl4r Very interested in the helper functions.  Plotdap was meant to be sort of a rerddap-ggplot.  Separate packages might be the way to go.  Do you have these on Github - I would like to look at them and play with them. I know others who would be interested in this.   Part of it is starting next Monday I will be away from work for a couple of weeks,  so that is one reason why I would not be working on it for awhile.  And yes,  I like to keep feature bloat down in any package.  Hard enough to maintain as is,  given all the options of ERDDAP.  plotdap was originally done as part of rerddap,  but it just made things too hard to maintain and debug.  So any thing you can point me to would be appreciated.

**Comment by 7yl4r** [comment]
The methods are scattered and messy right now but shouldn't be too much work to collect together. Do you have a particular repo you want to use these with? I could try to submit a PR.

**Comment by rmendels** [comment]
@7yl4r  Why don't you put them in a repo on your github,  and add them to r-universe.  I will talk to others about adding them to some of tutorial sites (I don't control those).  We are always interested in anything that makes it easier to for people to benefit from ERDDAP services.
