### ISSUE TITLE
Failure message

### ISSUE THREAD

**Issue by rvaillancourt** [ropensci/rerddap#115]
I am trying to download data from the OOI ERDDAP Tabledap using this R-script but keep getting the same error message.  The failure occurs after one or several downloads, but never on the same file.  I've copied the error message below, and also the R-script written by Ian Black below that.  

*******Error message*************
Error in download.file(file_url, destination, mode = "w") : 
  download from 'https://gliders.ioos.us/erddap/tabledap/cp_374-20150509T1256-delayed.csv?' failed
In addition: Warning message:
In download.file(file_url, destination, mode = "w") :
  URL 'https://gliders.ioos.us/erddap/tabledap/cp_374-20150509T1256-delayed.csv': status was 'Failure when receiving data from the peer'

*************End of error message************

************Complete R-script************
# Install required packages.
pkgs <- c('ncdf4','rerddap')
install.packages(pkgs)

library('rerddap')

save_directory = 'C:/Users/rvaillancourt/OneDrive - Millersville University/Documents/AA_Pioneer Array/Glider Data by Year and Month/2014-2022_May2024/'  # Need a / on the end to signify a directory.

download_gliderdac_file <- function(dataset_id, save_dir, timeout= 60*1440){
  options(timeout = timeout)
  base = 'https://gliders.ioos.us/erddap/tabledap/'
  file_url = paste(base, dataset_id,'.csv?',sep = '')
  destination = paste(save_dir,dataset_id, '.csv',sep = '')
  download.file(file_url,destination, mode = 'w')
}

server <- 'https://gliders.ioos.us/erddap/'
all_deployments = global_search(query = 'size', server, 'tabledap')
all_datasets = unlist(all_deployments[2], use.names = FALSE)  # Get all deployments available through the GliderDAC ERDDAP.
pioneer_datasets = c()  # Holder for PA gliders.
for (i in 1:length(all_datasets)){
  if (grepl('cp_', all_datasets[i])){   # Only keep PA glider deployments.
    pioneer_datasets = c(pioneer_datasets,c(all_datasets[i]))
  }
}

timeout = 60*1440
for (j in 1:length(pioneer_datasets)){
  dataset_id = pioneer_datasets[j+3]
  download_gliderdac_file(dataset_id, save_directory, timeout)
}

****************end of R script**************************

**Comment by rmendels** [comment]
@rvaillancourt  I will try to help as best I can,  but please note this is not an 'rerddap' problem.  The only place 'rerddap' is used is the line:

```r
all_deployments = global_search(query = 'size', server, 'tabledap')
```
Actual downloads are using the base R command 'download.file()'.  It looks like you are trying to download entire files after converting to .csv.  These files can get very big,  even more so if translated to .csv.  It looks like you are timing out either because it is taking too long to translate or you have piled too many requests at once.  You would do much better downloading the 'native' netcdf file and translating on your machine using 'file' requests,  such as for your use the URL would start with:

https://gliders.ioos.us/erddap/files/cp_374-20150509T1256-delayed/

end with the file name say:

https://gliders.ioos.us/erddap/files/cp_374-20150509T1256-delayed/cp_374_20150509T132421Z_delayed.nc

and then using 'ncdf4' or 'raster' or the like to read the data into R.   I have no idea who Ian Black is,  but I would either talk to him or modify the script yourself if you are proficient in R.  Moreover,  you should put the "download.file()" in "try" and make certain one request has completed before sending another,  and if a download fails say wait 10 seconds and retry.

**Comment by rvaillancourt** [comment]
Thanks for your feedback, Roy. I will work with Ian on improving this script.  The script is also timing out if I request *.nc files, but they’re only about ½ the size of the *.csv files so we may have to slow the train down to make it work.

All the best,
-Bob.



Robert D. Vaillancourt, Ph.D.
Professor of Oceanography
106 Brossman Hall
Millersville University
Millersville, PA 17551
Office phone: 717 – 871- 4190

**Comment by rmendels** [comment]
@rvaillancourt   From the help for 'download.file()'

The timeout for many parts of the transfer can be set by the option timeout which defaults to 60 seconds. This is often insufficient for downloads of large files (50MB or more) and so should be increased when download.file is used in packages to do so. Note that the user can set the default timeout by the environment variable R_DEFAULT_INTERNET_TIMEOUT in recent versions of R, so to ensure that this is not decreased packages should use something like

    options(timeout = max(300, getOption("timeout")))
  
(It is unrealistic to require download times of less than 1s/MB.)

The level of detail provided during transfer can be set by the quiet argument and the internet.info option: the details depend on the platform and scheme. For the "libcurl" method values of the option less than 2 give verbose output.

**Comment by rmendels** [comment]
I am closing this because is not an rerddap issue.  The main problem was not changing the timeout value in download.file()
